import Link from "next/link";
import SystemUniverse from "./SystemUniverse";
import LatestSystems from "./LatestSystems";
import TechArsenal from "./TechArsenal";
import { getPublicProfile, getPublicProjects, getPublicPublications, getPublicSkills } from "../lib/public-api";

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";

export default async function Home() {
  const [profile, projects, publications, skills] = await Promise.all([getPublicProfile(), getPublicProjects(), getPublicPublications(), getPublicSkills()]);
  const nodes = [
    { id: "software", label: "SOFTWARE", detail: "Full-stack products, APIs, databases, and dependable delivery.", kind: "system" },
    { id: "ai", label: "AI / ML", detail: "Models and data workflows translated into useful systems.", kind: "intelligence" },
    { id: "research", label: "RESEARCH", detail: `${publications.length} research records connected to experiments.`, kind: "evidence" },
    { id: "security", label: "SECURITY", detail: "Network intelligence, detection, and resilient engineering.", kind: "security" },
    { id: "projects", label: "EXPERIMENTS", detail: `${projects.length} systems built and documented as case studies.`, kind: "work" },
  ];
  const uniqueTechnologies = new Set(projects.flatMap(p => p.project_technology?.map(t => t.technology.id) ?? [])).size;
  const metric = (label: string, value: string) => <div className="metric-box"><small>{label}</small><strong>{value}</strong><i /></div>;

  return <main className="public-system benchmark-system">
    <header className="public-nav benchmark-nav"><Link href="/" className="public-logo">AYUSH.HR<span>.</span><small>ENGINEERING SYSTEMS</small></Link><nav><a href="#universe">INDEX</a><a href="#systems">SYSTEMS</a><a href="#research">RESEARCH</a><Link href="/journey">JOURNEY</Link></nav><a className="nav-command" href={`mailto:${profile?.email ?? "hello@ayushraiyan.dev"}`}>CONTACT <span>â†’</span></a></header>
    <aside className="system-index benchmark-rail"><span>00 â€” HOME</span><a href="#universe">01 â€” INDEX</a><a href="#systems">02 â€” SYSTEMS</a><a href="#lab">03 â€” LAB</a><a href="#research">04 â€” RESEARCH</a><Link href="/journey">05 â€” JOURNEY</Link><a href="#contact">06 â€” CONTACT</a><div className="rail-social"><a href={profile?.github_url ?? "#"}>GH</a><a href={profile?.linkedin_url ?? "#"}>IN</a><a href={`mailto:${profile?.email ?? "hello@ayushraiyan.dev"}`}>âœ‰</a></div><small className="rail-copyright">SOFTWARE Ã— INTELLIGENCE<br />RESEARCH Ã— SYSTEMS</small></aside>
    <section className="system-hero benchmark-hero" id="top"><div className="hero-command"><span className="online"><i /> SYSTEM ONLINE</span><span>[ 00 : 52 : 11 ]<br />{(profile?.location ?? "BANGLADESH").toUpperCase()}</span></div><div className="hero-grid"><div className="hero-statement"><p className="eyebrow">I&apos;M <b>{(profile?.name ?? "AYUSH HASSAN RAIYAN").toUpperCase()}</b> â†’</p><h1>I BUILD<br /><em>INTELLIGENT</em><br />SYSTEMS<br />THAT MATTER.</h1><p>{profile?.bio ?? "Software engineering, AI/ML, and research brought together with clarity and intent."}</p><div className="hero-roles"><span>SOFTWARE ENGINEER</span><b>â€¢</b><span>AI / ML</span><b>â€¢</b><span>RESEARCHER</span></div><div className="hero-actions"><a className="command-button" href="#universe">EXPLORE MY UNIVERSE <span>â†’</span></a>{profile?.resume_url && <a className="command-button quiet" href={profile.resume_url} target="_blank" rel="noreferrer">VIEW RESUME â†“</a>}</div></div><div className="hero-core benchmark-core" aria-label="Engineered intelligence core"><div className="core-orbit orbit-a" /><div className="core-orbit orbit-b" /><div className="core-orbit orbit-c" /><div className="core-sculpture"><span>AI</span><small>ENGINEERED<br />INTELLIGENCE</small></div><div className="core-pulse" /></div><div className="metric-stack">{metric("PROJECTS", String(projects.length).padStart(2, "0"))}{metric("PUBLICATIONS", String(publications.length).padStart(2, "0"))}{metric("TECHNOLOGIES", String(uniqueTechnologies).padStart(2, "0"))}{metric("COFFEE", "âˆž")}</div></div><div className="hero-footer"><span>SCROLL TO EXPLORE</span><span>01 â€” 05</span></div></section>
    <section className="benchmark-workbench" id="universe"><div className="section-bar"><span>{"//"} EXPLORE MY UNIVERSE</span><small>INTERCONNECTED PRACTICE MAP</small></div><div className="workbench-grid"><SystemUniverse nodes={nodes} /><aside className="ask-panel"><span className="eyebrow">â—‰ ASK AYUSH</span><small>AI / ASSISTANT</small><div className="ask-wave">âŒâŒâŒâŒâŒâŒ</div><p>What kind of projects have you built?</p><p>Tell me about your research.</p><p>What technologies do you use?</p><p>How can we work together?</p><a href={`mailto:${profile?.email ?? "hello@ayushraiyan.dev"}`}>Ask anything... <b>â†’</b></a></aside></div></section>
    <section className="systems-section benchmark-systems" id="systems"><div className="section-bar"><span>{"//"} LATEST SYSTEMS</span><Link href="/projects">VIEW ALL SYSTEMS â†’</Link></div><div className="system-grid">{projects.map((p, i) => <Link className={`system-card ${i === 0 ? "featured" : ""}`} href={`/projects/${p.slug}`} key={p.slug}><span className="card-number">{String(i + 1).padStart(2, "0")}</span>{p.project_media?.[0] && <img src={`${api}/media/${p.project_media[0].media.storage_key}`} alt="" />}<div className="card-content"><small>{(p.status ?? "PROJECT SYSTEM").toUpperCase()}</small><h2>{p.title}</h2><p>{p.description}</p><div className="card-tech">{p.project_technology?.slice(0, 4).map(x => <span key={x.technology.id}>{x.technology.name}</span>)}</div><b>VIEW SYSTEM â†’</b></div></Link>)}</div></section>
    <section className="benchmark-triad" id="lab"><article><div className="section-bar"><span>{"//"} ABOUT ME</span></div><p>{profile?.bio ?? "A software engineer building scalable systems with intelligence, clarity, and purpose."}</p><pre>{`const ayush = {\n  focus: [software, ai, research],\n  systems: true,\n};`}</pre><Link className="command-button quiet" href="/journey">MORE ABOUT ME -&gt;</Link></article><article><div className="section-bar"><span>{"//"} SYSTEM METRICS</span></div><div className="metric-pair"><strong>{projects.length}+</strong><small>PROJECTS BUILT</small><strong>{publications.length}</strong><small>PUBLICATIONS</small></div><div className="signal-chart"><span /><span /><span /><span /><span /><span /><span /></div></article><article><div className="section-bar"><span>{"//"} TECH ARSENAL</span></div><TechArsenal skills={skills} /><div className="arsenal-links"><Link className="text-link" href="/skills">SHOW ALL SKILLS -&gt;</Link><Link className="text-link" href="/projects">SEE TECHNOLOGY IN SYSTEMS -&gt;</Link></div></article></section>
    <section className="research-section benchmark-research" id="research"><div className="section-bar"><span>{"//"} RESEARCH RECORD</span><Link href="/publications">VIEW ALL PUBLICATIONS â†’</Link></div><div className="research-layout"><h2>Built systems.<br /><em>Published thinking.</em></h2><div>{publications.slice(0, 3).map((p, i) => <Link className="research-row" href="/publications" key={p.id}><span>0{i + 1}</span><div><small>{p.venue ?? "RESEARCH RECORD"}</small><strong>{p.title}</strong></div><b>â†—</b></Link>)}</div></div></section>
    <footer className="public-footer benchmark-footer" id="contact"><div><strong>â€œTHE BEST WAY TO PREDICT THE FUTURE<br />IS TO INVENT IT.â€ <small>â€” ALAN KAY</small></strong><span className="footer-invite">LET&apos;S BUILD THE FUTURE TOGETHER.</span><a className="command-button" href={`mailto:${profile?.email ?? "hello@ayushraiyan.dev"}`}>GET IN TOUCH â†’</a></div><span>Â© {new Date().getFullYear()} {profile?.name ?? "Ayush Hassan Raiyan"} / SOFTWARE Ã— INTELLIGENCE Ã— RESEARCH</span></footer>
  </main>;
}

