"use client";
import { useState } from "react";

type Node = { id: string; label: string; detail: string; kind: string };

export default function SystemUniverse({ nodes }: { nodes: Node[] }) {
  const [active, setActive] = useState(nodes[0]?.id ?? "");
  const selected = nodes.find(node => node.id === active) ?? nodes[0];
  return <div className="universe-shell"><div className="universe-visual" aria-label="Interactive technical universe"><svg viewBox="0 0 760 430" role="img"><g className="universe-lines">{nodes.map((node, index) => { const angle = (index / nodes.length) * Math.PI * 2 - Math.PI / 2; const x = 380 + Math.cos(angle) * 215; const y = 215 + Math.sin(angle) * 150; return <line key={node.id} className={active === node.id ? "active" : ""} x1="380" y1="215" x2={x} y2={y} />; })}</g><g className="universe-orbits"><ellipse cx="380" cy="215" rx="190" ry="94" /><ellipse cx="380" cy="215" rx="218" ry="130" /><ellipse cx="380" cy="215" rx="150" ry="72" /><ellipse cx="380" cy="215" rx="105" ry="50" /></g><circle className="universe-core-glow" cx="380" cy="215" r="38" /><circle className="universe-core" cx="380" cy="215" r="9" />{nodes.map((node, index) => { const angle = (index / nodes.length) * Math.PI * 2 - Math.PI / 2; const x = 380 + Math.cos(angle) * 215; const y = 215 + Math.sin(angle) * 150; return <g key={node.id} className={active === node.id ? "universe-node active" : "universe-node"} onClick={() => setActive(node.id)} role="button" tabIndex={0} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") setActive(node.id); }}><circle cx={x} cy={y} r="16" /><circle className="node-dot" cx={x} cy={y} r="4" /><text x={x + (x < 380 ? -22 : 22)} y={y + (y < 215 ? -20 : 26)} textAnchor={x < 380 ? "end" : "start"}>{node.label}</text></g>; })}</svg><button className="enter-universe" type="button" onClick={() => setActive(nodes[(nodes.findIndex(node => node.id === active) + 1) % nodes.length]?.id ?? "")}>ENTER UNIVERSE <span>◎</span></button></div><div className="universe-inspector"><span className="eyebrow">Selected system</span><strong>{selected?.label}</strong><p>{selected?.detail}</p><span className="system-state"><i /> Connected to the portfolio graph</span></div></div>;
}
