"use client";

const marks: Record<string, { slug: string; color: string; group: string }> = {
  Python: { slug: "python", color: "3776ab", group: "LANGUAGES" }, JavaScript: { slug: "javascript", color: "f7df1e", group: "LANGUAGES" }, TypeScript: { slug: "typescript", color: "3178c6", group: "LANGUAGES" }, Java: { slug: "openjdk", color: "ed8b00", group: "LANGUAGES" }, "C++": { slug: "cplusplus", color: "00599c", group: "LANGUAGES" }, HTML: { slug: "html5", color: "e34f26", group: "LANGUAGES" }, CSS: { slug: "css3", color: "1572b6", group: "LANGUAGES" },
  React: { slug: "react", color: "61dafb", group: "FRAMEWORKS" }, "Next.js": { slug: "nextdotjs", color: "ffffff", group: "FRAMEWORKS" }, PHP: { slug: "php", color: "777bb4", group: "FRAMEWORKS" }, Bootstrap: { slug: "bootstrap", color: "7952b3", group: "FRAMEWORKS" }, "Scikit-learn": { slug: "python", color: "f7931e", group: "LIBRARIES" }, Pandas: { slug: "pandas", color: "150458", group: "LIBRARIES" }, NumPy: { slug: "numpy", color: "4dabcf", group: "LIBRARIES" }, Matplotlib: { slug: "python", color: "11557c", group: "LIBRARIES" }, Seaborn: { slug: "python", color: "3776ab", group: "LIBRARIES" },
  PostgreSQL: { slug: "postgresql", color: "4169e1", group: "DATABASES" }, MySQL: { slug: "mysql", color: "4479a1", group: "DATABASES" }, Redis: { slug: "redis", color: "dc382d", group: "DATABASES" }, SQL: { slug: "sqlite", color: "9baec2", group: "DATABASES" },
  Docker: { slug: "docker", color: "2496ed", group: "TOOLS" }, Git: { slug: "git", color: "f05032", group: "TOOLS" }, GitHub: { slug: "github", color: "ffffff", group: "TOOLS" }, "Google Colab": { slug: "google", color: "f9ab00", group: "TOOLS" }, "Visual Studio Code": { slug: "visualstudiocode", color: "007acc", group: "TOOLS" }, XAMPP: { slug: "xampp", color: "fb7a24", group: "TOOLS" }, cPanel: { slug: "cpanel", color: "ff6c2c", group: "TOOLS" }, NetBeans: { slug: "netbeans", color: "1b6ac6", group: "TOOLS" }, "Microsoft Office": { slug: "microsoftoffice", color: "d83b01", group: "TOOLS" }, "Google Workspace": { slug: "googleworkspace", color: "4285f4", group: "TOOLS" }, LaTeX: { slug: "latex", color: "008080", group: "TOOLS" }, "Cisco Packet Tracer": { slug: "cisco", color: "1ba0d7", group: "TOOLS" }, Prisma: { slug: "prisma", color: "ffffff", group: "TOOLS" }, Figma: { slug: "figma", color: "f24e1e", group: "TOOLS" },
};

export default function TechArsenal({ skills }: { skills: { id: string; name: string }[] }) {
  const grouped = new Map<string, typeof skills>();
  skills.forEach(skill => { const group = marks[skill.name]?.group ?? "TOOLS"; grouped.set(group, [...(grouped.get(group) ?? []), skill]); });
  return <div className="arsenal-groups">{["LANGUAGES", "FRAMEWORKS", "LIBRARIES", "DATABASES", "TOOLS"].map(group => <div className="arsenal-group" key={group}><small>{group}</small><div>{(grouped.get(group) ?? []).map(skill => { const mark = marks[skill.name]; return mark ? <span className="arsenal-logo" title={skill.name} key={skill.id}><img src={`https://cdn.simpleicons.org/${mark.slug}/${mark.color}`} alt={skill.name} onError={event => { event.currentTarget.closest(".arsenal-logo")?.remove(); }} /></span> : null; })}</div></div>)}</div>;
}
