import Link from "next/link";
import SkillIcon from "../../skills/SkillIcon";
import type { PublicEducation, PublicExperience, PublicPublication, PublicSkill } from "../../../lib/public-api";
import styles from "./CapabilityTrajectory.module.css";

type Props = { skills: PublicSkill[]; education: PublicEducation[]; experience: PublicExperience[]; publications: PublicPublication[] };
const t=(d?:string|null)=>d?new Date(d).getTime()||0:0;
const f=(d?:string|null)=>d?new Intl.DateTimeFormat("en-US",{month:"short",year:"numeric"}).format(new Date(d)).toUpperCase():"";
function latest<T extends {start_date:string;end_date:string|null}>(a:T[]){return a.filter(x=>!x.end_date).sort((x,y)=>t(y.start_date)-t(x.start_date))[0]??[...a].sort((x,y)=>t(y.end_date??y.start_date)-t(x.end_date??x.start_date))[0];}
export default function CapabilityTrajectory({skills,education,experience,publications}:Props){const stack=skills.filter(x=>x.featured).sort((a,b)=>(a.sort_order??1e9)-(b.sort_order??1e9)).slice(0,9);const work=latest(experience),study=latest(education);const research=[...publications].sort((a,b)=>Number(b.featured)-Number(a.featured)||t(b.publication_date)-t(a.publication_date)).slice(0,2);if(!stack.length&&!work&&!study&&!research.length)return null;return <section className={styles.section} aria-label="Portfolio signals"><Panel label="// CORE STACK" title="Selected stack" meta={`${String(stack.length).padStart(2,"0")} / FEATURED`}><div className={styles.stackGrid}>{stack.map((s,i)=><div className={styles.stackItem} key={s.id}><span className={styles.stackIndex}>{String(i+1).padStart(2,"0")}</span><span className={styles.stackIcon}><SkillIcon name={s.name} category={s.category} size={31}/></span><strong>{s.name}</strong><i/></div>)}</div><Foot text="FULL CAPABILITY INDEX" href="/skills" action="VIEW SKILLS"/></Panel><Panel label="// TRAJECTORY" title="Current vector" live><div className={styles.trajectory}>{work&&<Rec type={!work.end_date?"CURRENT WORKPLACE":"RECENT WORKPLACE"} title={work.company} href={work.company_url} role={work.position} start={work.start_date} end={work.end_date} location={work.location}/>} {study&&<Rec type={!study.end_date?"CURRENT EDUCATION":"RECENT EDUCATION"} title={study.institution} href={study.institution_url} role={`${study.degree}${study.field?` / ${study.field}`:""}`} start={study.start_date} end={study.end_date}/>}</div><Foot text="FULL CHRONOLOGY" href="/journey" action="VIEW JOURNEY"/></Panel><Panel label="// RESEARCH SIGNAL" title="Published work" meta={`${String(publications.length).padStart(2,"0")} / RECORDS`}><div className={styles.researchRecords}>{research.map((p,i)=><article className={styles.researchRecord} key={p.id}><div className={styles.researchTop}><span>{String(i+1).padStart(2,"0")}</span><small>{p.publication_date?.slice(0,4)}</small></div><h3>{p.title}</h3>{p.venue&&<span>{p.venue}</span>}<div className={styles.researchLinks}>{p.paper_url&&<a href={p.paper_url} target="_blank" rel="noreferrer">PAPER ↗</a>}{p.notebook_url&&<a href={p.notebook_url} target="_blank" rel="noreferrer">NOTEBOOK ↗</a>}</div></article>)}</div><Foot text="RESEARCH ARCHIVE" href="/research" action="EXPLORE RESEARCH"/></Panel></section>}
function Panel({label,title,meta,live,children}:{label:string;title:string;meta?:string;live?:boolean;children:React.ReactNode}){return <article className={styles.panel}><header className={styles.panelHeader}><div><span className={styles.eyebrow}>{label}</span><h2>{title}</h2></div>{live?<span className={styles.liveMeta}><i/> LIVE RECORD</span>:<span className={styles.panelMeta}>{meta}</span>}</header>{children}</article>}
function Foot({text,href,action}:{text:string;href:string;action:string}){return <footer className={styles.panelFooter}><span>{text}</span><Link href={href}>{action} <b>↗</b></Link></footer>}
function Rec({type,title,href,role,start,end,location}:{type:string;title:string;href:string|null;role:string;start:string;end:string|null;location?:string|null}){return <div className={styles.trajectoryRecord}><span className={styles.timelineNode}/><div className={styles.recordContent}><span className={styles.recordType}>{type}</span><h3>{href?<a href={href} target="_blank" rel="noreferrer">{title}</a>:title}</h3><strong>{role}</strong><div className={styles.recordMeta}><span>{f(start)} — {end?f(end):"PRESENT"}</span>{location&&<span>{location}</span>}</div></div></div>}
