"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Skill={id:string;name:string;category:string;proficiency:number|null;sort_order:number;featured:boolean};
const api=process.env.NEXT_PUBLIC_ADMIN_API_URL??"http://localhost:4000";
const proficiencyOptions=[[1,"Beginner"],[2,"Intermediate"],[3,"Proficient"],[4,"Advanced"],[5,"Expert"]] as const;
export default function SkillsPage(){const [items,setItems]=useState<Skill[]>([]),[editingId,setEditingId]=useState<string|null>(null);const [name,setName]=useState(""),[category,setCategory]=useState(""),[proficiency,setProficiency]=useState(""),[sortOrder,setSortOrder]=useState("0"),[featured,setFeatured]=useState(false),[message,setMessage]=useState("");
async function load(){const r=await fetch(`${api}/admin/library/skills`,{credentials:"include"});if(r.status===401){window.location.replace("/login");return []}if(!r.ok)throw new Error();return r.json() as Promise<Skill[]>}
useEffect(()=>{let active=true;void load().then(v=>{if(active)setItems(v)}).catch(()=>{if(active)setMessage("Could not load skills.")});return()=>{active=false}},[]);
function resetForm(){setEditingId(null);setName("");setCategory("");setProficiency("");setSortOrder("0");setFeatured(false)}
function editSkill(item:Skill){setEditingId(item.id);setName(item.name);setCategory(item.category);setProficiency(item.proficiency==null?"":String(item.proficiency));setSortOrder(String(item.sort_order??0));setFeatured(item.featured??false);setMessage("");window.scrollTo({top:0,behavior:"smooth"})}
async function save(event:FormEvent){event.preventDefault();const body={name,category,proficiency:proficiency?Number(proficiency):null,sort_order:Number(sortOrder)||0,featured};const id=editingId;const r=await fetch(id?`${api}/admin/library/skills/${id}`:`${api}/admin/library/skills`,{method:id?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setMessage(id?"Could not update skill.":"Could not save skill.");return}setItems(await load());setMessage(id?"Skill updated.":"Skill added.");resetForm()}
async function removeSkill(id:string){if(!window.confirm("Remove this skill?"))return;const r=await fetch(`${api}/admin/library/skills/${id}`,{method:"DELETE",credentials:"include"});if(!r.ok){setMessage("Could not remove skill.");return}setItems(await load());if(editingId===id)resetForm();setMessage("Skill removed.")}
return <main className="editor-shell"><header className="editor-header"><Link className="admin-brand" href="/">AHR<span>.</span><small>studio / capabilities</small></Link><Link className="editor-back" href="/">← Overview</Link></header><section className="editor-grid"><form className="project-form" onSubmit={save}><p className="admin-kicker">{editingId?"Edit capability":"Add capability"}</p><label>Skill or technology<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Category<input required placeholder="AI / ML, Software / Web…" value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Proficiency<select value={proficiency} onChange={e=>setProficiency(e.target.value)}><option value="">Not specified</option>{proficiencyOptions.map(([value,label])=><option value={value} key={value}>{value} — {label}</option>)}</select></label><label>Display priority<input type="number" min="0" step="1" value={sortOrder} onChange={e=>setSortOrder(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/><span>Featured Skill</span></label><div className="form-actions"><button type="submit">{editingId?"Update skill":"Add skill"}</button>{editingId&&<button className="secondary-action" type="button" onClick={resetForm}>Cancel</button>}</div>{message&&<p className="editor-message">{message}</p>}</form><div className="project-list"><p className="admin-kicker">Capability map · {items.length}</p>{items.length===0&&<p className="empty-editor">No skills added yet.</p>}{items.map((item,index)=><article className="project-row" key={item.id}><span>{String(index+1).padStart(2,"0")}</span><div><strong>{item.name}</strong><p>{item.category}{item.proficiency==null?" · Proficiency not specified":` · Level ${item.proficiency}/5`}</p></div><button type="button" onClick={()=>editSkill(item)}>Edit</button><button className="delete-action" type="button" onClick={()=>void removeSkill(item.id)} aria-label={`Delete ${item.name}`}>×</button></article>)}</div></section></main>}


