"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Publication = { id:string; title:string; venue:string|null; publication_date:string|null; paper_url:string|null; repository_url:string|null; description:string|null; featured:boolean };
const api=process.env.NEXT_PUBLIC_ADMIN_API_URL??"http://localhost:4000";
const empty={title:"",venue:"",publication_date:"",paper_url:"",repository_url:"",description:"",featured:false};
export default function PublicationsPage(){const [items,setItems]=useState<Publication[]>([]);const [form,setForm]=useState(empty);const [editing,setEditing]=useState<string|null>(null);const [message,setMessage]=useState("");
async function load(){const r=await fetch(`${api}/admin/library/publications`,{credentials:"include"});if(r.status===401){window.location.replace("/login");return [];}return r.json() as Promise<Publication[]>;}useEffect(()=>{void load().then(setItems).catch(()=>setMessage("Could not load publications."));},[]);
async function save(e:FormEvent){e.preventDefault();const r=await fetch(`${api}/admin/library/publications${editing?`/${editing}`:""}`,{method:editing?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!r.ok){const d=await r.json().catch(()=>null) as {message?:string}|null;setMessage(d?.message??`Could not save publication (${r.status}).`);return;}setItems(await load());setForm(empty);setEditing(null);setMessage("Publication saved.");}
return <main className="editor-shell"><header className="editor-header"><Link className="admin-brand" href="/">AHR<span>.</span><small>studio / publications</small></Link><Link className="editor-back" href="/">{"ÃƒÂ¢Ã¢â‚¬Â Ã‚Â"} Overview</Link></header><section className="editor-intro"><p className="admin-kicker">Research / Publications</p><h1>Give the work<br/><em>its record.</em></h1><p>Keep titles, venues, links, and research records verified.</p></section><section className="editor-grid"><form className="project-form" onSubmit={save}><p className="admin-kicker">{editing?"Edit record":"New record"}</p><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Venue<input value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}/></label><label>Publication date<input type="date" value={form.publication_date} onChange={e=>setForm({...form,publication_date:e.target.value})}/></label><label>Paper URL<input type="url" value={form.paper_url} onChange={e=>setForm({...form,paper_url:e.target.value})}/></label><label>Notebook / repository URL<input type="url" value={form.repository_url} onChange={e=>setForm({...form,repository_url:e.target.value})}/></label><label>Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="checkbox-field"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured publication</label><button type="submit">{editing?"Update record":"Create record"}</button>{message&&<p className="editor-message">{message}</p>}</form><div className="project-list"><p className="admin-kicker">Research records / {items.length}</p>{items.map((item,index)=><article className="project-row" key={item.id}><span>0{index+1}</span><div><strong>{item.title}</strong><p>{item.venue??"Venue not set"}</p></div><button type="button" onClick={()=>{setEditing(item.id);setForm({title:item.title,venue:item.venue??"",publication_date:item.publication_date?.slice(0,10)??"",paper_url:item.paper_url??"",repository_url:item.repository_url??"",description:item.description??"",featured:item.featured});}}>Edit</button></article>)}</div></section></main>}







