"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Publication = { id: string; title: string; venue: string | null; publication_date: string | null; doi_url: string | null; paper_url: string | null; description: string | null; featured: boolean };
const api = process.env.NEXT_PUBLIC_ADMIN_API_URL ?? "http://localhost:4000";
const empty = { title: "", venue: "", publication_date: "", doi_url: "", paper_url: "", description: "", featured: false };
export default function PublicationsPage() { const [items, setItems] = useState<Publication[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState("");
  async function load() { const response = await fetch(`${api}/admin/library/publications`, { credentials: "include" }); if (response.status === 401) { window.location.replace("/login"); return []; } if (!response.ok) throw new Error("Could not load publications"); return response.json() as Promise<Publication[]>; }
  useEffect(() => { let active = true; void load().then((value) => { if (active) setItems(value); }).catch(() => { if (active) setMessage("Could not load publications."); }); return () => { active = false; }; }, []);
  async function save(event: FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch(`${api}/admin/library/publications${editing ? `/${editing}` : ""}`, { method: editing ? "PUT" : "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) { setMessage("Could not save publication."); return; } setItems(await load()); setForm(empty); setEditing(null); setMessage("Publication saved."); }
  return <main className="editor-shell"><header className="editor-header"><Link className="admin-brand" href="/">AHR<span>.</span><small>studio / publications</small></Link><Link className="editor-back" href="/">← Overview</Link></header><section className="editor-intro"><p className="admin-kicker">Research / Publications</p><h1>Give the work<br /><em>its record.</em></h1><p>Keep titles, venues, authorship, and links verified. Research earns its visual weight through precision.</p></section><section className="editor-grid"><form className="project-form" onSubmit={save}><p className="admin-kicker">{editing ? "Edit record" : "New record"}</p><label>Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Venue<input value={form.venue} onChange={(e) => setForm({ ...form, venue: e.target.value })} /></label><label>Publication date<input type="date" value={form.publication_date} onChange={(e) => setForm({ ...form, publication_date: e.target.value })} /></label><label>Paper URL<input type="url" value={form.paper_url} onChange={(e) => setForm({ ...form, paper_url: e.target.value })} /></label><label>Description<textarea rows={4} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button type="submit">{editing ? "Update record" : "Create record"}</button>{message && <p className="editor-message">{message}</p>}</form><div className="project-list"><p className="admin-kicker">Research records · {items.length}</p>{items.map((item, index) => <article className="project-row" key={item.id}><span>0{index + 1}</span><div><strong>{item.title}</strong><p>{item.venue ?? "Venue not set"}</p></div><button type="button" onClick={() => { setEditing(item.id); setForm({ title: item.title, venue: item.venue ?? "", publication_date: item.publication_date?.slice(0, 10) ?? "", doi_url: item.doi_url ?? "", paper_url: item.paper_url ?? "", description: item.description ?? "", featured: item.featured }); }}>Edit</button></article>)}</div></section></main>; }
