"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Project={title:string;slug:string;description:string;github_url:string|null;live_url:string|null;featured:boolean;sort_order:number}; type Technology={id:string;name:string;category:string|null};
const api=process.env.NEXT_PUBLIC_ADMIN_API_URL??"http://localhost:4000"; const empty:Project={title:"",slug:"",description:"",github_url:"",live_url:"",featured:false,sort_order:0};
export default function ProjectsPage(){const [items,setItems]=useState<Project[]>([]),[techs,setTechs]=useState<Technology[]>([]),[selected,setSelected]=useState<string[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState("");
 async function load(){const r=await fetch(`${api}/admin/projects`,{credentials:"include"});if(r.status===401){window.location.replace("/login");return [];}return r.json() as Promise<Project[]>;} useEffect(()=>{void Promise.all([load(),fetch(`${api}/admin/library/technologies`,{credentials:"include"}).then(r=>r.json() as Promise<Technology[]>)]).then(([p,t])=>{setItems(p);setTechs(t);}).catch(()=>setMessage("Could not load projects."));},[]);
 async function save(e:FormEvent){e.preventDefault();const r=await fetch(`${api}/admin/projects${editing?`/${editing}`:""}`,{method:editing?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!r.ok){setMessage("Could not save project.");return;}const p=await r.json() as Project;await fetch(`${api}/admin/projects/${p.slug}/technologies`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({technologyIds:selected})});setItems(await load());setForm(empty);setSelected([]);setEditing(null);setMessage("Project saved.");} async function edit(p:Project){setEditing(p.slug);setForm(p);const r=await fetch(`${api}/admin/projects/${p.slug}/technologies`,{credentials:"include"});if(r.ok){const links=await r.json() as {technology:{id:string}}[];setSelected(links.map(x=>x.technology.id));}}
 return <main className="editor-shell"><header className="editor-header"><Link className="admin-brand" href="/">AHR<span>.</span><small>studio / projects</small></Link><Link className="editor-back" href="/">← Overview</Link></header><section className="editor-intro"><p className="admin-kicker">Content / Projects</p><h1>Build the<br/><em>case studies.</em></h1><p>Connect each project to the technologies that prove how it was made.</p></section><section className="editor-grid"><form className="project-form" onSubmit={save}><p className="admin-kicker">{editing?"Edit project":"New project"}</p><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Slug<input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Description<textarea required rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Repository URL<input type="url" value={form.github_url??""} onChange={e=>setForm({...form,github_url:e.target.value})}/></label><label>Live URL<input type="url" value={form.live_url??""} onChange={e=>setForm({...form,live_url:e.target.value})}/></label><fieldset className="technology-picker"><legend>Technologies used</legend>{techs.length?techs.map(t=><label className="technology-option" key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={()=>setSelected(ids=>ids.includes(t.id)?ids.filter(id=>id!==t.id):[...ids,t.id])}/>{t.name}</label>):<small>No technology records yet.</small>}</fieldset><button type="submit">{editing?"Update project":"Create project"}</button>{message&&<p className="editor-message">{message}</p>}</form><div className="project-list"><p className="admin-kicker">Current projects · {items.length}</p>{items.map((p,i)=><article className="project-row" key={p.slug}><span>0{i+1}</span><div><strong>{p.title}</strong><p>{p.description}</p></div><button type="button" onClick={()=>void edit(p)}>Edit</button></article>)}</div></section></main>}
