"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
type Project={title:string;slug:string;summary:string|null;description:string;status:string;image_url:string|null;github_url:string|null;live_url:string|null;featured:boolean;sort_order:number};type Asset={id:string;storage_key:string};
const api=process.env.NEXT_PUBLIC_ADMIN_API_URL??"http://localhost:4000";const empty:Project={title:"",slug:"",summary:"",description:"",status:"draft",image_url:"",github_url:"",live_url:"",featured:false,sort_order:0};
export default function ProjectsPage(){const [items,setItems]=useState<Project[]>([]),[media,setMedia]=useState<Asset[]>([]),[form,setForm]=useState(empty),[selectedMedia,setSelectedMedia]=useState<string[]>([]),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState("");
async function load(){const r=await fetch(`${api}/admin/projects`,{credentials:"include"});return r.json() as Promise<Project[]>}useEffect(()=>{void Promise.all([load(),fetch(`${api}/admin/media`,{credentials:"include"}).then(r=>r.json() as Promise<Asset[]>)]).then(([p,m])=>{setItems(p);setMedia(m)}).catch(()=>setMessage("Could not load projects."))},[]);
async function save(e:React.FormEvent){e.preventDefault();const r=await fetch(`${api}/admin/projects${editing?`/${editing}`:""}`,{method:editing?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!r.ok){setMessage("Could not save project.");return}const p=await r.json() as Project;await fetch(`${api}/admin/projects/${p.slug}/media`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({mediaIds:selectedMedia})});setItems(await load());setForm(empty);setSelectedMedia([]);setEditing(null);setMessage("Project saved.")}
async function edit(p:Project){setEditing(p.slug);setForm({...p,summary:p.summary??""});const r=await fetch(`${api}/admin/projects/${p.slug}/media`,{credentials:"include"});if(r.ok)setSelectedMedia((await r.json() as {media_id:string}[]).map(x=>x.media_id))}function choose(asset:Asset){const ids=selectedMedia.includes(asset.id)?selectedMedia.filter(id=>id!==asset.id):[...selectedMedia,asset.id];setSelectedMedia(ids);const primary=media.find(x=>x.id===ids[0]);setForm({...form,image_url:primary?`${api}/media/${primary.storage_key}`:null})}
return <main className="editor-shell"><header className="editor-header"><Link className="admin-brand" href="/">AHR<span>.</span><small>studio / projects</small></Link><Link className="editor-back" href="/">← Overview</Link></header><section className="editor-intro"><p className="admin-kicker">Content / Projects</p><h1>Build the<br/><em>case studies.</em></h1><p>Select multiple reusable Media assets. The first selected image is the primary project image.</p></section><section className="editor-grid"><form className="project-form" onSubmit={save}><p className="admin-kicker">{editing?"Edit project":"New project"}</p><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Slug<input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Summary<textarea value={form.summary??""} onChange={e=>setForm({...form,summary:e.target.value})} placeholder="Short recruiter-facing summary for the project hero." rows={3}/></label><label>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="planned">Planned</option><option value="ongoing">Ongoing</option><option value="finished">Finished</option><option value="paused">Paused</option><option value="archived">Archived</option></select></label><label className="check-row"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/><span>Featured Project</span></label><div className="media-picker-block"><strong>Project images · {selectedMedia.length} selected</strong><div className="media-picker">{media.map(x=><button type="button" key={x.id} className={selectedMedia.includes(x.id)?"media-picker-option selected":"media-picker-option"} onClick={()=>choose(x)}><img src={`${api}/media/${x.storage_key}`} alt=""/><span>{x.storage_key.slice(0,8)}…</span></button>)}</div></div><label>Repository URL<input type="url" value={form.github_url??""} onChange={e=>setForm({...form,github_url:e.target.value})}/></label><label>Live URL<input type="url" value={form.live_url??""} onChange={e=>setForm({...form,live_url:e.target.value})}/></label><button type="submit">{editing?"Update project":"Create project"}</button>{message&&<p className="editor-message">{message}</p>}</form><div className="project-list"><p className="admin-kicker">Current projects · {items.length}</p>{items.map((p,i)=><article className="project-row" key={p.slug}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{p.title}</strong><p>{p.description}</p></div><button type="button" onClick={()=>void edit(p)}>Edit</button></article>)}</div></section></main>}
